name: Secret Scan
on: [push, pull_request]

jobs:
  leash-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: FasterApiWeb/leash-secrets/action@leash-secrets-v1.1.0
        with:
          scan-mode: diff
          fail-on: critical
          exclude: 'node_modules/**,.git/**'
